### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by shiyuw3** [Jokeren/GPA#1]
Hi, I am trying to compile with v1.1. branch but failed (just run ``./bin/install.sh``, tried different methods but didnot work... the failure log is:

libtool: link: g++ -g -O3 -Wall -faligned-new -I/home/shiyuw3/Research/GPA/hpctoolkit/build/../src -I/home/shiyuw3/Research/GPA/hpctoolkit/build/src -I/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/include -fopenmp -g -O3 -Wall -faligned-new -o hpcstruct-bin hpcstruct_bin-main.o hpcstruct_bin-Args.o  -lm ../../../src/lib/analysis/.libs/libHPCanalysis.a ../../../src/lib/banal/.libs/libHPCbanal.a ../../../src/lib/banal/.libs/libHPCbanal_simple.a ../../../src/lib/cuda/.libs/libHPCcuda.a ../../../src/lib/prof/.libs/libHPCprof.a ../../../src/lib/binutils/.libs/libHPCbinutils.a ../../../src/lib/prof-lean/.libs/libHPCprof-lean.a ../../../src/lib/isa/.libs/libHPCisa.a -L/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/intel-xed-12.0.1-yrgrijqrgszo5awltzwmh4ciqiejflc4/lib -lxed ../../../src/lib/xml/.libs/libHPCxml.a ../../../src/lib/support/.libs/libHPCsupport.a ../../../src/lib/support-lean/.libs/libHPCsupport-lean.a -L/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/dyninst-master-6c5ar22gudnpp6efyjmwabnfg2ubnfpd/lib -lparseAPI -linstructionAPI -lsymtabAPI -ldynDwarf -ldynElf -lcommon -L/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/boost-1.78.0-ycm4c7bdfy2aj72wltvm4urrtolzevxh/lib -lboost_graph -lboost_regex -lboost_system -L/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/elfutils-0.186-wrfkscknrznfmlxxa6iud5yclvpuc44b/lib -ldw -lelf /home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a /home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libiberty.a -ldl /home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/zlib-1.2.11-7vrl3cv4xoyo4w3qvjwqeowjrzkg6qtc/lib/libz.a -L/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/xz-5.2.5-edaifsp5xaetukjfkr62o2rnah4dyhrl/lib -llzma -L/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/intel-tbb-2020.3-qlx6t3m6czclmn5sgnx26chv2mudmwcb/lib -ltbb -ltbbmalloc -fopenmp
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elflink.o): In function `init_reloc_cookie':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elflink.c:12965: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elflink.o): In function `elf_link_read_relocs_from_section':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elflink.c:2551: undefined reference to `libintl_dgettext'
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elflink.c:2539: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elflink.o): In function `check_dynsym':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elflink.c:9640: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elflink.o): In function `undefined_reference':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elflink.c:8475: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elflink.o):/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elflink.c:8630: more undefined references to `libintl_dgettext' follow
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elf64-ppc.o): In function `ppc64_elf_build_stubs':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elf64-ppc.c:14125: undefined reference to `libintl_dngettext'
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elf64-ppc.c:14129: undefined reference to `libintl_dgettext'
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elf64-ppc.c:14111: undefined reference to `libintl_dgettext'
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/elf64-ppc.c:14089: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elf32-riscv.o): In function `riscv_make_plt_entry':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/./elfnn-riscv.c:217: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elf32-riscv.o): In function `bad_static_reloc':
/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/./elfnn-riscv.c:510: undefined reference to `libintl_dgettext'
/home/shiyuw3/Research/GPA/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/lib/libbfd.a(elf32-riscv.o):/tmp/shiyuw3/spack-stage/spack-stage-binutils-2.34-kmdpaev3aoxm7rvtjffo4lapqzt4em57/spack-src/bfd/./elfnn-riscv.c:509: more undefined references to `libintl_dgettext' follow
collect2: error: ld returned 1 exit status
Makefile:718: recipe for target 'hpcstruct-bin' failed
make[4]: *** [hpcstruct-bin] Error 1

Appreciate for any help, thanks ahead!

Some references:
https://github.com/spack/spack/issues/2613
https://www.gnu.org/software/gettext/FAQ.html#integrating_undefined

**Comment by Jokeren** [comment]
It may have to do with the spack version you used, since GPA depends on a relatively old spack.

Can you please try this first? If it does not work, I'll try to find the right commond using the latest spack.

> git clone https://github.com/Jokeren/spack.git && cd spack && git pull origin && git checkout 58a919d1677e0b172ec250b8dd84a1eb32efa366

**Comment by shiyuw3** [comment]
> It may have to do with the spack version you used, since GPA depends on a relatively old spack.
> 
> Can you please try this first? If it does not work, I'll try to find the right commond using the latest spack.
> 
> > git clone https://github.com/Jokeren/spack.git && cd spack && git pull origin && git checkout 58a919d1677e0b172ec250b8dd84a1eb32efa366

kk, no problem. I will try the old version first. Thanks!

**Comment by shiyuw3** [comment]
> It may have to do with the spack version you used, since GPA depends on a relatively old spack.
> 
> Can you please try this first? If it does not work, I'll try to find the right commond using the latest spack.
> 
> > git clone https://github.com/Jokeren/spack.git && cd spack && git pull origin && git checkout 58a919d1677e0b172ec250b8dd84a1eb32efa366

Seems did not work though :(

**Comment by Jokeren** [comment]
@shiyuw3 I just updated install.sh, can you please try it again?

**Comment by shiyuw3** [comment]
> @shiyuw3 I just updated install.sh, can you please try it again?

Yes it works now, thanks!
