### ISSUE TITLE
GPA advice not generated

### ISSUE THREAD

**Issue by shiyuw3** [Jokeren/GPA#2]
Hi I followed the instruction on https://github.com/Jokeren/GPA/blob/master/INSTALL.md, but there is no advice file generated after executing gpa, any advice?

**Comment by Jokeren** [comment]
That might be difficult to debug. 

If you append `-v` to `gpa`, then you will see a `gpa.log` file generated. Please copy and paste the content of the log file here.

And make sure you use *cuda < 11.1*. I haven't integrated the source code parsing support for *cuda >= 11.2* to this branch.

**Comment by jmellorcrummey** [comment]
@Jokeren isn't the advice file written into the database directory? Perhaps Shiyu isn't looking in the right place for the advice.

**Comment by Jokeren** [comment]
Yes, the gpa.advice file is under `./gpa-database`

**Comment by shiyuw3** [comment]
My bad, after struggling I have generated the advice file successfully, thanks for the help!
